
branches:
  only:
  - master

dist: trusty
language: minimal

jobs:
  include:
    - stage: release
      script:
      - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      - make build DEBUG=false
      - make tag_latest DEBUG=false
      - make release DEBUG=false
      - curl -s -X POST "https://hooks.microbadger.com/images/${TRAVIS_REPO_SLUG}/jaJQb-O_tU-ZppG--6GHnJSaiBU="